# Generated by Django 3.2.6 on 2022-12-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Waktu')),
                ('biaya', models.CharField(blank=True, max_length=30, null=True, verbose_name='Biaya')),
                ('proyek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyek.proyek')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ('user',),
            },
        ),
    ]
