# Generated by Django 3.2.6 on 2022-12-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Data')),
                ('waktu', models.DateTimeField()),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ('nama_data',),
            },
        ),
    ]
