# Generated by Django 3.2.6 on 2022-12-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='proyek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyek.proyek'),
        ),
    ]
