# Generated by Django 3.2.6 on 2022-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='nama_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Data'),
        ),
    ]
