# Generated by Django 3.2.6 on 2022-12-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Kegiatan')),
                ('kode', models.CharField(blank=True, max_length=255, null=True)),
                ('predecessor', models.CharField(blank=True, max_length=255, null=True)),
                ('hubungan_keterkaitan', models.CharField(blank=True, choices=[('-', '-'), ('S-S', 'Start to Start'), ('F-S', 'Finish to Start'), ('F-F', 'Finish to Finish')], default='ss', max_length=255, null=True)),
                ('bobot_kegiatan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bobot Kegiatan')),
                ('proyek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyek.proyek')),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Estimasi_Waktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimasi_waktu_a', models.FloatField(blank=True, null=True, verbose_name='Optimistic Time')),
                ('estimasi_waktu_m', models.FloatField(blank=True, null=True, verbose_name='Most Likely Time')),
                ('estimasi_waktu_b', models.FloatField(blank=True, null=True, verbose_name='Pessismistic Time')),
                ('expected_duration', models.FloatField(blank=True, null=True, verbose_name='Expected Duration')),
                ('kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.kegiatan')),
            ],
            options={
                'verbose_name': 'Estimasi Waktu',
                'verbose_name_plural': 'Estimasi Waktu',
                'ordering': ('kegiatan',),
            },
        ),
        migrations.CreateModel(
            name='Estimasi_Biaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimasi_biaya', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Perkiraan Biaya')),
                ('kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.kegiatan')),
            ],
            options={
                'verbose_name': 'Estimasi Biaya',
                'verbose_name_plural': 'Estimasi Biaya',
                'ordering': ('kegiatan',),
            },
        ),
    ]
