# Generated by Django 3.2.6 on 2022-12-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=255, null=True, verbose_name='Nama Kegiatan')),
                ('kode', models.CharField(blank=True, max_length=255, null=True)),
                ('predecessor', models.CharField(blank=True, max_length=255, null=True)),
                ('hubungan_keterkaitan', models.CharField(blank=True, choices=[('', '-'), ('S-S', 'Start to Start'), ('F-S', 'Finish to Start'), ('F-F', 'Finish to Finish')], default='ss', max_length=255, null=True)),
                ('bobot_kegiatan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Bobot Kegiatan')),
                ('biaya_kegiatan', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Biaya Kegiatan')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('standar_deviasi', models.FloatField(blank=True, null=True, verbose_name='Standar Deviasi')),
                ('varians_kegiatan', models.FloatField(blank=True, null=True, verbose_name='Varians Kegiatan')),
                ('earliest_start', models.FloatField(blank=True, null=True, verbose_name='ES')),
                ('earliest_finish', models.FloatField(blank=True, null=True, verbose_name='EF')),
                ('latest_start', models.FloatField(blank=True, null=True, verbose_name='LS')),
                ('latest_finish', models.FloatField(blank=True, null=True, verbose_name='LF')),
                ('slack_time', models.FloatField(blank=True, null=True, verbose_name='Slack')),
                ('critical', models.CharField(blank=True, max_length=255, null=True)),
                ('successors', models.CharField(blank=True, max_length=255, null=True)),
                ('proyek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyek.proyek')),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Estimasi_Waktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimasi_waktu_a', models.FloatField(blank=True, null=True, verbose_name='Optimistic Time')),
                ('estimasi_waktu_m', models.FloatField(blank=True, null=True, verbose_name='Most Likely Time')),
                ('estimasi_waktu_b', models.FloatField(blank=True, null=True, verbose_name='Pessismistic Time')),
                ('kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.kegiatan')),
            ],
            options={
                'verbose_name': 'Estimasi Waktu',
                'verbose_name_plural': 'Estimasi Waktu',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Estimasi_Biaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcws', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Budgeted Cost of Work Schedule')),
                ('bcwp', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Budgeted Cost of Work Planned ')),
                ('acwp', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Actual Cost of Work Planned')),
                ('kegiatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.kegiatan')),
            ],
            options={
                'verbose_name': 'Estimasi Biaya',
                'verbose_name_plural': 'Estimasi Biaya',
                'ordering': ('id',),
            },
        ),
    ]
