# Generated by Django 3.2.6 on 2022-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimasi_waktu',
            name='standar_deviasi',
            field=models.FloatField(blank=True, null=True, verbose_name='Standar Deviasi'),
        ),
    ]
