# Generated by Django 3.2.6 on 2022-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_estimasi_waktu_standar_deviasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimasi_waktu',
            name='varians_kegiatan',
            field=models.FloatField(blank=True, null=True, verbose_name='Varians Kegiatan'),
        ),
    ]
