# Generated by Django 3.2.6 on 2022-12-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Proyek')),
                ('SPK', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek',
                'ordering': ('nama_proyek',),
            },
        ),
    ]
