# Generated by Django 3.2.6 on 2022-12-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimasi_waktu',
            options={'ordering': ('kode',), 'verbose_name': 'Estimasi Waktu', 'verbose_name_plural': 'Estimasi Waktu'},
        ),
    ]
