# Generated by Django 3.2.6 on 2022-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyek',
            name='tanggal_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai'),
        ),
        migrations.AddField(
            model_name='proyek',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai'),
        ),
    ]
